//Including required tools
#include "lidar_pose_estimator/lidar_pose_estimator_node.hpp"
#include <tf2_eigen/tf2_eigen.hpp>
#include <pcl/common/transforms.h>
#include <cmath>
#include <cstdlib>

namespace lidar_pose_estimator

{
LidarPoseEstimatorNode::LidarPoseEstimatorNode(const rclcpp::NodeOptions & options)
: Node("lidar_pose_estimator", options)
{
  //Parameters and values
  lidar_topic_           = declare_parameter<std::string>("lidar_topic",           "/iv_points_fusion");
  map_pcd_path_          = declare_parameter<std::string>("map_pcd_path",          "/tmp/lidar_map.pcd");
  tum_path_              = declare_parameter<std::string>("tum_path",              "/tmp/lidar_tum.txt");

  ndt_resolution_        = declare_parameter<double>("ndt_resolution",             0.5);
  ndt_step_size_         = declare_parameter<double>("ndt_step_size",              0.05);
  ndt_epsilon_           = declare_parameter<double>("ndt_epsilon",                1e-4);
  ndt_max_iter_          = declare_parameter<int>   ("ndt_max_iter",               60);
  ndt_fitness_threshold_ = declare_parameter<double>("ndt_fitness_threshold",      0.5);
  voxel_leaf_size_       = declare_parameter<double>("voxel_leaf_size",            0.1);
  map_voxel_leaf_size_   = declare_parameter<double>("map_voxel_leaf_size",        0.1);
  max_scan_range_        = declare_parameter<double>("max_scan_range",             40.0);
  min_scan_range_        = declare_parameter<double>("min_scan_range",             1.0);
  ndt_max_points_        = declare_parameter<int>   ("ndt_max_points",             10000);
  map_publish_every_     = declare_parameter<int>   ("map_publish_every",          5);
  map_min_points_        = declare_parameter<int>   ("map_min_points",             150000);
  map_revoxel_every_     = declare_parameter<int>   ("map_revoxel_every",          50);

  //Configuring NDT
  ndt_.setResolution(static_cast<float>(ndt_resolution_));
  ndt_.setStepSize(static_cast<float>(ndt_step_size_));
  ndt_.setTransformationEpsilon(ndt_epsilon_);
  ndt_.setMaximumIterations(ndt_max_iter_);

  //Map cloud variable
  map_cloud_ = std::make_shared<pcl::PointCloud<pcl::PointXYZ>>();

  //frame ID --> (map) for bith lidar estimator and evaluator
  lidar_path_msg_.header.frame_id = "map";

  //Openning TUM file
  tum_file_.open(tum_path_);
  if (!tum_file_.is_open()) {
    RCLCPP_WARN(get_logger(), "Could not open TUM file at '%s'", tum_path_.c_str());
  } else {
    tum_file_ << "# TUM format: timestamp tx ty tz qx qy qz qw\n";
    tum_file_ << "# Generated by lidar_pose_estimator — LiDAR-only NDT\n";
  }

  // Subscriber
  cloud_sub_ = create_subscription<sensor_msgs::msg::PointCloud2>(
    lidar_topic_,
    rclcpp::QoS(rclcpp::KeepLast(100)).best_effort().durability_volatile(),
    std::bind(&LidarPoseEstimatorNode::cloudCallback, this, std::placeholders::_1));
    //large queue so bag playback never drops frames

  //Publishers
  odom_pub_ = create_publisher<nav_msgs::msg::Odometry>("/lidar_odom", 10);

  map_pub_ = create_publisher<sensor_msgs::msg::PointCloud2>(
    "/map_cloud",
    rclcpp::QoS(rclcpp::KeepLast(1)).reliable().transient_local());

  pose_pub_       = create_publisher<geometry_msgs::msg::PoseStamped>("/lidar_pose", 10);
  lidar_path_pub_ = create_publisher<nav_msgs::msg::Path>("/lidar_path", 10);

  tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(*this);

  //Logging info
  RCLCPP_INFO(get_logger(),
    "LidarPoseEstimatorNode (NDT) ready.\n"
    "  lidar topic           -> %s\n"
    "  map PCD               -> %s\n"
    "  TUM output            -> %s\n"
    "  ndt_resolution        -> %.2f\n"
    "  ndt_step_size         -> %.3f\n"
    "  ndt_fitness_threshold -> %.2f\n"
    "  voxel_leaf_size       -> %.2f m\n"
    "  map_voxel_leaf_size   -> %.2f m\n"
    "  scan range            -> [%.1f, %.1f] m\n"
    "  ndt_max_points        -> %d\n"
    "  map_revoxel_every     -> %d frames\n"
    "Waiting for first scan...",
    lidar_topic_.c_str(), map_pcd_path_.c_str(), tum_path_.c_str(),
    ndt_resolution_, ndt_step_size_, ndt_fitness_threshold_,
    voxel_leaf_size_, map_voxel_leaf_size_,
    min_scan_range_, max_scan_range_,
    ndt_max_points_, map_revoxel_every_);
}

//cloudCallback (main pipeline) 
void LidarPoseEstimatorNode::cloudCallback(
  const sensor_msgs::msg::PointCloud2::SharedPtr msg)
{
  // Convert ROS → PCL
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_in(new pcl::PointCloud<pcl::PointXYZ>);
  pcl::fromROSMsg(*msg, *cloud_in);

  //Voxel-downsample
  pcl::VoxelGrid<pcl::PointXYZ> vg;
  vg.setLeafSize(
    static_cast<float>(voxel_leaf_size_),
    static_cast<float>(voxel_leaf_size_),
    static_cast<float>(voxel_leaf_size_));
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);
  vg.setInputCloud(cloud_in);
  vg.filter(*cloud_filtered);

  if (cloud_filtered->empty()) {
    RCLCPP_WARN(get_logger(), "Empty filtered cloud at frame %d — skipping.", frame_count_);
    return;
  }

  //Range filter — remove points too close (noise)
 
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_range(new pcl::PointCloud<pcl::PointXYZ>);
  cloud_range->reserve(cloud_filtered->size());
  const float min_r2 = static_cast<float>(min_scan_range_ * min_scan_range_);
  const float max_r2 = static_cast<float>(max_scan_range_ * max_scan_range_);
  for (const auto & pt : *cloud_filtered) {
    const float r2 = pt.x * pt.x + pt.y * pt.y + pt.z * pt.z;
    if (r2 >= min_r2 && r2 <= max_r2) {
      cloud_range->push_back(pt);
    }
  }

  if (cloud_range->empty()) {
    RCLCPP_WARN(get_logger(),
      "Empty range-filtered cloud at frame %d (range [%.1f, %.1f] m) — skipping.",
      frame_count_, min_scan_range_, max_scan_range_);
    return;
  }

  //Use range-filtered cloud for all subsequent processing
  cloud_filtered = cloud_range;

  //This is done AFTER voxel+range filtering so the spatial distribution remains uniform
  if (static_cast<int>(cloud_filtered->size()) > ndt_max_points_) {
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_sub(new pcl::PointCloud<pcl::PointXYZ>);
    cloud_sub->reserve(ndt_max_points_);
    const float keep_ratio = static_cast<float>(ndt_max_points_) /
                             static_cast<float>(cloud_filtered->size());
    for (const auto & pt : *cloud_filtered) {
      if (static_cast<float>(rand()) / static_cast<float>(RAND_MAX) < keep_ratio) {
        cloud_sub->push_back(pt);
        if (static_cast<int>(cloud_sub->size()) >= ndt_max_points_) break;
      }
    }
    cloud_filtered = cloud_sub;
  }

  //Always log point count for first 20 frames so tuning is visible
  if (frame_count_ < 20) {
    RCLCPP_INFO(get_logger(),
      "Frame %d: %zu pts after voxel+range+cap filter  "
      "(raw=%zu  voxel_leaf=%.2f  range=[%.1f,%.1f]m  max_pts=%d)",
      frame_count_, cloud_filtered->size(), cloud_in->size(),
      voxel_leaf_size_, min_scan_range_, max_scan_range_, ndt_max_points_);
  }

  //Bootstrap: first scan seeds the map at identity
  if (!initialized_) {
    prev_cloud_  = cloud_filtered;
    T_map_lidar_.setIdentity();
    T_delta_.setIdentity();
    initialized_ = true;

    //Accumulate first scan directly (it IS in map frame at identity)
    accumulateMap(cloud_filtered);

    //Publish everything so path starts from frame 0 with no delay
    publishAll(msg->header.stamp);
    logTum(msg->header.stamp);

    frame_count_++;
    //Printing log info data
    RCLCPP_INFO(get_logger(),
      "Bootstrap complete — first scan added (%zu pts).", cloud_filtered->size());
    return;
  }

  /* [Constant-velocity motion prior]
   * T_delta_ = incremental transform from the last two successful frames.
   * Extrapolating it forward gives a linearised initial guess that is much closer to the true pose*/
  Eigen::Isometry3d initial_guess = T_map_lidar_ * T_delta_;

  //NDT scan matching
  //scan-to-map once the map is dense enough
  const bool use_map = (static_cast<int>(map_cloud_->size()) >= map_min_points_);
  ndt_.setInputSource(cloud_filtered);
  ndt_.setInputTarget(use_map ? map_cloud_ : prev_cloud_);

  pcl::PointCloud<pcl::PointXYZ>::Ptr ndt_output(new pcl::PointCloud<pcl::PointXYZ>);
  ndt_.align(*ndt_output, initial_guess.matrix().cast<float>());

  double fitness   = ndt_.getFitnessScore();
  bool   converged = ndt_.hasConverged() && (fitness < ndt_fitness_threshold_);

  //Fallback to scan-to-scan if scan-to-map diverged (which is like a backup scanning)
  if (!converged && use_map) {
    RCLCPP_WARN(get_logger(),
      "Frame %d: scan-to-map NDT diverged (fitness=%.4f) — retrying scan-to-scan",
      frame_count_, fitness);

    ndt_.setInputTarget(prev_cloud_);
    ndt_.align(*ndt_output, initial_guess.matrix().cast<float>());

    fitness   = ndt_.getFitnessScore();
    converged = ndt_.hasConverged() && (fitness < ndt_fitness_threshold_ * 2.0);
  }

  //Accept or reject
  if (converged) {
    Eigen::Isometry3d T_new;
    T_new.matrix() = ndt_.getFinalTransformation().cast<double>();

    //Only update motion prior when match is good
    T_delta_     = T_map_lidar_.inverse() * T_new;
    T_map_lidar_ = T_new;

    consecutive_failures_ = 0;

    RCLCPP_INFO(get_logger(),
      "Frame %4d  fitness=%.4f  pos=[%.2f, %.2f, %.2f]",
      frame_count_, fitness,
      T_map_lidar_.translation().x(),
      T_map_lidar_.translation().y(),
      T_map_lidar_.translation().z());
  } else {
    consecutive_failures_++;
    RCLCPP_ERROR(get_logger(),
      "Frame %d: NDT diverged (fitness=%.4f, consecutive failures=%d) — holding last pose",
      frame_count_, fitness, consecutive_failures_);
    //T_map_lidar_ and T_delta_ are intentionally NOT updated.
  }

   // Accumulate FULL filtered scan transformed with current pose
   // Transforming the full filtered scan ensures every received point enters the map instead of transforming only ndt-output.
   
  {
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_in_map(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::transformPointCloud(
      *cloud_filtered, *cloud_in_map,
      T_map_lidar_.matrix().cast<float>());
    accumulateMap(cloud_in_map);
  }

  //Publishing all outputs
  publishAll(msg->header.stamp);
  logTum(msg->header.stamp);

  if (frame_count_ % map_publish_every_ == 0) {
    publishMap();
  }

  prev_cloud_ = cloud_filtered;
  frame_count_++;
}

//accumulateMap
void LidarPoseEstimatorNode::accumulateMap(
  const pcl::PointCloud<pcl::PointXYZ>::Ptr & cloud_in_map)
{
  *map_cloud_ += *cloud_in_map;

  if (frame_count_ % map_revoxel_every_ == 0 && !map_cloud_->empty()) {
    pcl::VoxelGrid<pcl::PointXYZ> vg;
    vg.setLeafSize(
      static_cast<float>(map_voxel_leaf_size_),
      static_cast<float>(map_voxel_leaf_size_),
      static_cast<float>(map_voxel_leaf_size_));
    vg.setInputCloud(map_cloud_);
    pcl::PointCloud<pcl::PointXYZ>::Ptr tmp(new pcl::PointCloud<pcl::PointXYZ>);
    vg.filter(*tmp);
    map_cloud_ = tmp;
    RCLCPP_INFO(get_logger(),
      "Map re-voxelised at frame %d: %zu points", frame_count_, map_cloud_->size());
  }
}

//publishAll — odometry, pose, TF, path in one call

void LidarPoseEstimatorNode::publishAll(const rclcpp::Time & stamp)
{
  const Eigen::Vector3d    pos(T_map_lidar_.translation());
  const Eigen::Quaterniond rot(T_map_lidar_.rotation());

  //Odom
  {
    nav_msgs::msg::Odometry odom;
    odom.header.stamp    = stamp;
    odom.header.frame_id = "map";
    odom.child_frame_id  = "lidar";
    odom.pose.pose.position.x    = pos.x();
    odom.pose.pose.position.y    = pos.y();
    odom.pose.pose.position.z    = pos.z();
    odom.pose.pose.orientation.w = rot.w();
    odom.pose.pose.orientation.x = rot.x();
    odom.pose.pose.orientation.y = rot.y();
    odom.pose.pose.orientation.z = rot.z();
    odom_pub_->publish(odom);
  }

  //PoseStamped
  {
    geometry_msgs::msg::PoseStamped ps;
    ps.header.stamp    = stamp;
    ps.header.frame_id = "map";
    ps.pose.position.x    = pos.x();
    ps.pose.position.y    = pos.y();
    ps.pose.position.z    = pos.z();
    ps.pose.orientation.w = rot.w();
    ps.pose.orientation.x = rot.x();
    ps.pose.orientation.y = rot.y();
    ps.pose.orientation.z = rot.z();
    pose_pub_->publish(ps);
  }

  //TF: map → lidar
  {
    geometry_msgs::msg::TransformStamped tf_msg =
      tf2::eigenToTransform(T_map_lidar_);
    tf_msg.header.stamp    = stamp;
    tf_msg.header.frame_id = "map";
    tf_msg.child_frame_id  = "lidar";
    tf_broadcaster_->sendTransform(tf_msg);
  }

  //Path
  {
    geometry_msgs::msg::PoseStamped ps;
    ps.header.stamp    = stamp;
    ps.header.frame_id = "map";
    ps.pose.position.x    = pos.x();
    ps.pose.position.y    = pos.y();
    ps.pose.position.z    = pos.z();
    ps.pose.orientation.w = rot.w();
    ps.pose.orientation.x = rot.x();
    ps.pose.orientation.y = rot.y();
    ps.pose.orientation.z = rot.z();

    lidar_path_msg_.header.stamp = stamp;
    lidar_path_msg_.poses.push_back(ps);
    lidar_path_pub_->publish(lidar_path_msg_);
  }
}

//publishMap
void LidarPoseEstimatorNode::publishMap()
{
  if (map_cloud_->empty()) return;

  sensor_msgs::msg::PointCloud2 map_msg;
  pcl::toROSMsg(*map_cloud_, map_msg);
  map_msg.header.frame_id = "map";
  map_msg.header.stamp    = get_clock()->now();
  map_pub_->publish(map_msg);

  RCLCPP_INFO(get_logger(),
    "Map published: %zu points (frame %d)", map_cloud_->size(), frame_count_);
}

//Adding data to Tum file
void LidarPoseEstimatorNode::logTum(const rclcpp::Time & stamp)
{
  if (!tum_file_.is_open()) return;

  const Eigen::Vector3d    t(T_map_lidar_.translation());
  const Eigen::Quaterniond q(T_map_lidar_.rotation());

  tum_file_
    << std::fixed << std::setprecision(9) << stamp.seconds() << " "
    << std::setprecision(6)
    << t.x() << " " << t.y() << " " << t.z() << " "
    << q.x() << " " << q.y() << " " << q.z() << " " << q.w()
    << "\n";
  tum_file_.flush();
}

// saveMap  (called on SIGINT)
void LidarPoseEstimatorNode::saveMap(const std::string & path)
{
  if (map_cloud_ && !map_cloud_->empty()) {
    pcl::io::savePCDFileBinary(path, *map_cloud_);
    RCLCPP_INFO(get_logger(),
      "Map saved to '%s'  (%zu points)", path.c_str(), map_cloud_->size());
  } else {
    RCLCPP_WARN(get_logger(), "Map cloud is empty — nothing saved.");
  }

  if (tum_file_.is_open()) {
    tum_file_.close();
    RCLCPP_INFO(get_logger(),
      "TUM file closed at '%s'", tum_path_.c_str());
  }
}

}


int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  auto node = std::make_shared<lidar_pose_estimator::LidarPoseEstimatorNode>();
  rclcpp::spin(node);
  node->saveMap(node->get_parameter("map_pcd_path").as_string());
  rclcpp::shutdown();
  return 0;
}
